In [101]:
from fugue_notebook import setup
setup ()

In [102]:
%%fsql dask
df = LOAD "C:/Users/SomeUser/.dagster/ashli/all_plants_shipping_receiving.csv" (header=true)
YIELD DATAFRAME AS df

In [103]:
df.as_pandas().sample(2).transpose()

,58894,153151
REPORT_ID,GPROD006,GPROD006
SUPP_NO,51628204,13250702
SUPP_NAME,ATLANTIC TOOL & DIE COMPANY,KASAI NORTH AMERICA INC
ORD_NO,155085.0,442264.0
PART_NO,38151T20 A000,8320BTLA A302
PART_CLR_CD,,NH836L
PART_DESC,"BRKT,HORN(UPR)",HEADLINER SUBASSY
DELV_SCDL_DT,2021-06-23 15:15:00,2021-06-23 02:15:00
SORTDATE,202106231515,202106230215
ASN_NO,00248440,00254137
ORDERED_QTY,1050,30
ASN_PART_QTY,1050,30
SHIPMENT_DT,20210622,20210623
SHIPMENT_TIME,80000,10000
PART_UNLD_QTY,0,0
TRLR_ARR_DT,,20210623
ASSOC_CD,VEC38378,VC043561
ASSOC_NAME,SHERY JERRY,JENNIFER DENNIS
SUPP_LOC,4,2
DATE,2021-06-23 15:15:00,2021-06-23 02:15:00
ORD_TYPE_CODE,DS,DS
SHORT_NAME_DESC,OPEN,LATE
MPL_NO,,
SHIP_TO_CD,SP11 01,MAP1 10
TRLR_ARR_TIME,,004337
TRLR_NO,778251,551402
RECEIPT_ADJ_TYPE,NaN,NaN
ADJ_TSTMP,2021-06-23 15:15:00,2021-06-23 02:15:00
RECEIPT_ADJ_NO,NaN,NaN
PLANT_CD,HCM,MAP
PLANT_DESC,HONDA OF CANADA MFG,MARYSVILLE AUTO PLANT
ASN_PART_QTY1,0,0
ADJ_QTY,0,0
DATE1,20210623,20210623
TOTAL_ASN_PART_QTY,1050,30
DC_SEG,00,02 01
ACTUAL_DT,20210622,20210622
ACTUAL_TIME,085800,233400

In [107]:
%%fsql
df = LOAD "C:/Users/MA17151/.dagster/ashli/all_plants_shipping_receiving.csv" (header=true)
ALTER COLUMNS
DELV_SCDL_DT: datetime,
DATE: datetime,
ADJ_TSTMP: datetime,
ASN_PART_QTY1: int,
ADJ_QTY: int,
TOTAL_ASN_PART_QTY: int
SELECT SUM(TOTAL_ASN_PART_QTY) AS Qty
PRINT

         Qty
0  101034939